### ISSUE TITLE
[modules/asg] Argument Deprecation Warning

### ISSUE THREAD

**Issue by migara** [PaloAltoNetworks/terraform-google-swfw-modules#14]
The current `asg` module throws a deprecation warning. We should change the [automatic](https://github.com/PaloAltoNetworks/terraform-google-swfw-modules/blob/ec3eb332343ca11348b5572b771a9a5fb2203ec9/modules/autoscale/main.tf#L244) argument to [auto](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#auto)

```
│ Warning: Argument is deprecated
│ 
│   with module.vmseries.google_secret_manager_secret.delicensing_cfn_pano_creds,
│   on .terraform/modules/vmseries/modules/autoscale/main.tf line 244, in resource "google_secret_manager_secret" "delicensing_cfn_pano_creds":
│  244:     automatic = true
│ 
│ `automatic` is deprecated and will be removed in a future major release. Use `auto` instead.

```

**Comment by michalbil** [comment]
This is at the moment the only outstanding item in #7
