### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by horiagunica** [PaloAltoNetworks/terraform-google-swfw-modules#3]
Add IPv6 support to modules and add one example to demonstrate usage in IPv6 environment. This should include the following:

- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #38
- [x] #40 
- [x] #21

**Comment by pavelrn** [comment]
- Support for dual-stack subnets (External IPv6 addresses) added into `modules/vpc`
- Support for dual-stack External L7 LB added into `modules/lb_http_ext_global`. The LB terminates IPv6 and uses IPv4 to communicate to the backend
