### ISSUE TITLE
LB module not setting balancing mode correctly. 

### ISSUE THREAD

**Issue by jollymahn** [PaloAltoNetworks/terraform-google-swfw-modules#34]
### Describe the bug

ERROR
problem occurs for both lb_internal and lb_external 

```
module.vpc_peering["trust-to-spoke2"].google_compute_network_peering.peer: Creation complete after 1m7s [id=sj-az-lab-fw-spoke2-vpc/sj-az-lab-fw-spoke2-vpc-sj-az-lab-fw-trust-vpc]
╷
│ Error: Error creating RegionBackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].balancingMode': 'UTILIZATION'. Balancing mode must be CONNECTION for an INTERNAL backend service., invalid
│ 
│   with module.lb_internal["internal-lb"].google_compute_region_backend_service.this,
│   on ../../modules/lb_internal/main.tf line 10, in resource "google_compute_region_backend_service" "this":
│   10: resource "google_compute_region_backend_service" "this" {
│ 
╵

```

PERMALINK

https://github.com/PaloAltoNetworks/terraform-google-swfw-modules/blob/bbd9e72306a20cf5ae4f86709c9cf670ca024d86/modules/lb_internal/main.tf#L23

RESOLUTION

 ```
 dynamic "backend" {
    for_each = var.backends
    content {
      group    = backend.value
      failover = false
      balancing_mode = "CONNECTION"
    }
  }
```

### Module Version

2.0.6

### Terraform version

1.6.0

### Expected behavior

successful LB deployment. 

### Current behavior

can not deploy load balancer frontend because backend not in supported mode. 

### Anything else to add?

 dynamic "backend" {
    for_each = var.backends
    content {
      group    = backend.value
      failover = false
      balancing_mode = "CONNECTION"
    }
  }

**Comment by pavelrn** [comment]
Hi @jollymahn ! What is `terraform providers --version` in your case?

**Comment by jollymahn** [comment]
M-L652YK23YP:.ssh sjolly$ terraform --version

Terraform v1.6.0

on darwin_arm64


Your version of Terraform is out of date! The latest version

is 1.9.5. You can update by downloading from
https://www.terraform.io/downloads.html



well, looks like its out of date... ill update it and try again.


Thank you!!


Sean


*Are you running a Preferred Software Release?
<https://live.paloaltonetworks.com/t5/Customer-Resources/Support-PAN-OS-Software-Release-Guidance/ta-p/258304>
Click
here for the latest information.*


Sean Jolly | Principal Professional Services Consultant- East Coast

Home Office: Knoxville, TN

HQ: Palo Alto Networks  |  3000 Tannery Way  |  Santa Clara, CA 95054  |  USA


Mobile: 865-804-3093  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

**Comment by pavelrn** [comment]
There was a [change](https://github.com/hashicorp/terraform-provider-google/commit/267f964bd4f2d9b48e8771c2a8397de3f6655ef7) in the `terraform-provider-google` version 6.0 default values that now requires explicitly set `balancing_mode`.
We need to adjust the module to be used with the newer provider version.
