### ISSUE TITLE
Unable to add alias ip range for vm series ha module

### ISSUE THREAD

**Issue by umangr036** [PaloAltoNetworks/terraform-google-swfw-modules#5]
### Describe the bug

Hi Team,

is it possible to add tf vars of how alias ip range can be given in this module. i am trying to do add it but not able to do that. the values are not getting picked up by the code

### Module Version

v1.3.2

### Expected behavior

na

### Current behavior

na

### Anything else to add?

na

**Comment by umangr036** [comment]
i think the alias_ip_ranges should be replaced with alias_ip_range. please let us know your review/comments on it

**Comment by horiagunica** [comment]
@umangr036 hello! Would you kindly share the code section with the `vmseries` module that you used and from which you got this error?

**Comment by umangr036** [comment]
dynamic "alias_ip_range" {
        for_each = try(network_interface.value.alias_ip_ranges, [])
        content {
          ip_cidr_range         = alias_ip_ranges.value.ip_cidr_range
          subnetwork_range_name = try(alias_ip_ranges.value.subnetwork_range_name, null)
        }
      }
    }
  }

#alias_ip_ranges should be replaced with alias_ip_range in the block
